#!/bin/bash

echo "This unit test will empty all events from Kde. Do you want to continue?"
echo "[y/N]"
read -n 1 reply
if [ "$reply" != "y" ]
then
        exit 1
fi

export KDE_DEBUG=true
osyncplugin kdepim --type event --plugindir ../.libs || exit 1
