#!/bin/bash

echo "This unit test will empty all notes from Kde. Do you want to continue?"
echo "[y/N]"
read -n 1 reply
if [ "$reply" != "y" ]
then
        exit 1
fi
export KDE_DEBUG=true
dcop knotes MainApplication-Interface quit
knotes
osyncplugin kdepim --type note || exit 1
dcop knotes MainApplication-Interface quit
