Import('*')

if env['enable_rpath'] == 1:
	env.Append( LINKFLAGS = [r'-Wl,--rpath', r'-Wl,$prefix/$libsuffix/opensync/formats'] )

#env.Append( LINKFLAGS = [r'-L$prefix/$libsuffix/opensync/formats'] )
env.Append( CPPPATH = '.' )


# build plugin
gpe_sync = env.SharedLibrary('gpe-sync', ['gpe_sync.c', 'calendar.c', 'contacts.c', 'todo.c', 'gpe_xml.c', 'gpesync_client.c', 'utils.c'], LIBS = ['opensync'])

# install synchronization plugin and config 
env.Install(install_plugin, gpe_sync)
env.Install(install_config, ['gpe-sync'])	

env.Alias('install', install_prefix)
