#!/bin/bash

echo "This unit test will empty all events from Opie. Do you want to continue?"
echo "[y/N]"
read -n 1 reply
if [ "$reply" != "y" ]
then
        exit 1
fi

osyncplugin opie-sync --type event --plugindir ../.libs || exit 1
