#!/bin/bash

echo "This unit test will empty all contacts from Opie. Do you want to continue?"
echo "[y/N]"
read -n 1 reply
if [ "$reply" != "y" ]
then
	exit 1
fi
osyncplugin opie-sync --type contact --plugindir ../src/.libs --config ../src/opie-sync || exit 1
