#ifndef _CONFIG_H_OPENSYNC
#define _CONFIG_H_OPENSYNC

#define OPENSYNC_PLUGINDIR "${OPENSYNC_PLUGINDIR}"
#define OPENSYNC_FORMATSDIR "${OPENSYNC_FORMATSDIR}"

#define OPENSYNC_CONFIGDIR "${OPENSYNC_CONFIGDIR}"

#define OPENSYNC_SCHEMASDIR "${OPENSYNC_SCHEMASDIR}"
#define OPENSYNC_DESCRIPTIONSDIR "${OPENSYNC_DESCRIPTIONSDIR}"
#define OPENSYNC_CAPABILITIESDIR "${OPENSYNC_CAPABILITIESDIR}"

#define OPENSYNC_VERSION "${OPENSYNC_VERSION}"

#define OPENSYNC_PLUGINVERSION ${OPENSYNC_PLUGINVERSION}

#define DEBUG_MODULES ${OPENSYNC_DEBUG_MODULES}
#define ENABLE_TRACE ${OPENSYNC_TRACE} 

#define OPENSYNC_TESTDATA "${CMAKE_CURRENT_SOURCE_DIR}/tests/data"

#endif /* _CONFIG_H_OPENSYNC */
