SET (CTEST_PROJECT_NAME "OpenSync" )
SET (CTEST_DROP_METHOD "xmlrpc" )
SET (CTEST_DROP_SITE "http://opensync.org/")
SET (CTEST_DROP_LOCATION "OpenSync")
SET (COMPRESS_SUBMISSON ON)
#SET (CTEST_TRIGGER_SITE "http://${CTEST_DROP_SITE}/cgi-bin/Submit-OpenSync-TestingResults.pl")
