#!/bin/bash

TMPDIR=`mktemp -d /tmp/osplg.XXXXXX` || exit 1

TMPCFG=`mktemp /tmp/osplgcfg.XXXXXX` || exit 1
echo "<config><path>$TMPDIR</path><recursive>FALSE</recursive></config>" > $TMPCFG

osyncplugin file-sync --config $TMPCFG --type data --plugin ../src/.libs/file_sync.so --format ../src/.libs/file.so || exit 1
