#!/bin/bash

echo "This unit test will empty all events from evolution2. Do you want to continue?"
echo "[y/N]"
read -n 1 reply
if [ "$reply" != "y" ]
then
        exit 1
fi

osyncplugin evo2-sync --config evo2-def.conf --type event || exit 1

osyncplugin evo2-sync --type event || exit 1