Import('*')

if testenv.has_key('enable_tests') and testenv['enable_tests'] == 1:
	support = testenv.Library('support', ['support.c'], LIBS = ['opensync', 'check'], LIBPATH = '#opensync')
	testenv.Program('error', ['check_error.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	testenv.Program('module', ['module-tests/check_module.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	testenv.Program('ipc', ['ipc-tests/check_ipc.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	testenv.Program('checkdata', ['data-tests/check_data.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	testenv.Program('conv', ['format-tests/check_conv.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	testenv.Program('converter', ['format-tests/check_converter.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	testenv.Program('formatenv', ['format-tests/check_format_env.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	testenv.Program('objformat', ['format-tests/check_objformat.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	#testenv.Program('merger', ['merger-tests/check_merger.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	testenv.Program('capabilities', ['merger-tests/check_capabilities.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	testenv.Program('archive', ['archive-tests/check_archive.c'], LIBS = ['opensync', 'check'], LIBPATH = '#opensync')
	testenv.Program('xmlformat', ['merger-tests/check_xmlformat.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	testenv.Program('client', ['client-tests/check_client.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	testenv.Program('proxy', ['client-tests/check_proxy.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	testenv.Program('mapping', ['mapping-tests/check_mapping.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	
	testenv.Program('engine', ['engine-tests/check_engine.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	testenv.Program('engine-error', ['engine-tests/check_engine_error.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	
	testenv.Program('sync', ['sync-tests/check_sync.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	
	testenv.SharedLibrary('mockformat', ['mock-plugin/mock_format.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
	testenv.SharedLibrary('mocksync', ['mock-plugin/mock_sync.c'], LIBS = ['opensync', 'check', support], LIBPATH = '#opensync')
