Import('*')

if testenv['enable_tests'] == 1:

        testenv.Append(LIBPATH = '.')

        support = testenv.Library('support', ['support.c'], LIBS = ['opensync', 'check'])
	conversion = testenv.Library('conversion', ['conversion-tests/conversion.c'], LIBS = ['opensync', 'check', support])

        testenv.Program('vcard', ['conversion-tests/check_vcard.c'], LIBS = ['opensync', 'check', support, conversion], LIBPATH = '$prefix/$libsuffix')
        testenv.Program('vevent', ['conversion-tests/check_vevent.c'], LIBS = ['opensync', 'check', support, conversion], LIBPATH = '$prefix/$libsuffix')
        testenv.Program('vtodo', ['conversion-tests/check_vtodo.c'], LIBS = ['opensync', 'check', support, conversion], LIBPATH = '$prefix/$libsuffix')
        testenv.Program('vnote', ['conversion-tests/check_vnote.c'], LIBS = ['opensync', 'check', support, conversion], LIBPATH = '$prefix/$libsuffix')

