#!/bin/bash

echo "This unit test will empty all tasks from evolution2. Do you want to continue?"
echo "[y/N]"
read -n 1 reply
if [ "$reply" != "y" ]
then
        exit 1
fi

TMPFILE=`mktemp /tmp/evo2-sync.XXXXXX` || exit 1
echo "<config><adress_path>default</adress_path><calendar_path>default</calendar_path><tasks_path>default</tasks_path></config>" > $TMPFILE

osyncplugin evo2-sync --config $TMPFILE --type todo --plugindir ../src/.libs || exit 1

rm -f $TMPFILE

