Import('env', 'install_lib', 'install_inc', 'install_prefix')

env.Append( CPPPATH = '.' )
env.Append( CPPPATH = '#' )

sources = """
osengine_message.c
osengine_queue.c
osengine_client.c
osengine_engine.c
osengine_status.c
osengine_debug.c
osengine_mapping.c
osengine_mapcmds.c
osengine_deciders.c
osengine_flags.c
"""

headers = """
engine.h
osengine_mapping.h
osengine_engine.h
osengine_status.h
osengine_debug.h
"""

libosengine = env.SharedLibrary('osengine', Split(sources))

env.Install(install_lib, libosengine)
env.Install(install_inc + '/opensync-1.0/osengine/', Split(headers))
env.Alias('install', install_prefix)
