Import('*')

env.Append( CPPPATH = '.' )

Libraries = r"""
glib-2.0
opensync
"""

vconvert = env.Program('vconvert', 'vconvert.c', LIBS = Split(Libraries))

env.Install(install_bin, vconvert)
env.Alias('install', install_prefix)
