Import('*')

import SCons.Script
import distutils.sysconfig


if env.has_key('enable_python') and env['enable_python'] == 1:

	SWIGScanner = SCons.Scanner.ClassicCPP(
	    "SWIGScan",
	    ".i",
	    "CPPPATH",
	    '^[ \t]*[%,#][ \t]*(?:include|import)[ \t]*(<|")([^>"]+)(>|")'
	)

	env.Append(SCANNERS=[SWIGScanner])
	env.Append(SWIGFLAGS = [r'-Werror', r'-Wall', r'-python', r'-modern', r'-I' + distutils.sysconfig.get_python_inc()])

	env.SharedLibrary('opensync', ['opensync.i'], LIBS = ['opensync'], LIBPATH = '#opensync')

