Import('*')

env.Append( CPPPATH = '.' )

syncml_plugin = env.SharedLibrary('syncml-plugin', ['syncml_plugin.c'], LIBS = ['opensync', 'syncml'])

# install synchronization plugin and config 
env.Install(install_plugin, syncml_plugin)
env.Install(install_config, ['syncml-obex-client'])
env.Install(install_config, ['syncml-http-server'])

env.Alias('install', install_prefix)
