Import('*')

formatenv = env.Copy()

if env['enable_rpath'] == 1:
	formatenv.Append( LINKFLAGS = [r'-Wl,--rpath', r'-Wl,$prefix/$libsuffix/opensync/formats'] )

formatenv.Append( LINKFLAGS = [r'-L$prefix/$libsuffix/opensync/formats'] )
formatenv.Append( CPPPATH = '.' )


# basic vformat plugins
file = formatenv.SharedLibrary('file', ['file.c'], LIBS = ['opensync'], LIBPATH = '#opensync')
data = formatenv.SharedLibrary('data', ['data.c'], LIBS = ['opensync'], LIBPATH = '#opensync')

# xmlformat support library which register xmlformat-contact, -event, -note, -todo
xmlformat = formatenv.SharedLibrary('xmlformat', ['xmlformat.c'], LIBS = ['opensync'], LIBPATH = '#opensync')

# xmlformat-doc library
xmlformatdoc = formatenv.SharedLibrary('xmlformat-doc', ['xmlformat-doc.c'], LIBS = ['opensync'], LIBPATH = '#opensync')

formatenv.Install(install_format, file)
formatenv.Install(install_format, data)
formatenv.Install(install_format, xmlformat)
formatenv.Install(install_format, xmlformatdoc)

formatenv.Install(install_inc + '/opensync-1.0/opensync/', 'file.h')

env.Alias('install', install_prefix)
