/*
 * xmlformat - registration of xml object formats 
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 * 
 */

#include "xmlformat-common.h"

#ifndef XMLFORMAT_CALENDAR_H
#define XMLFORMAT_CALENDAR_H

#define XMLFORMAT_CALENDAR_ROOT				"note"
#define XMLFORMAT_CALENDAR_VERSION			"version"

// Alarm
#define XMLFORMAT_CALENDAR_ALARM			"Alarm"
#define XMLFORMAT_CALENDAR_ALARM_ACTION			"AlarmAction"
#define XMLFORMAT_CALENDAR_ALARM_ACTION_AUDIO		"AUDIO"	
#define XMLFORMAT_CALENDAR_ALARM_ACTION_DISPLAY		"DISPLAY"	
#define XMLFORMAT_CALENDAR_ALARM_ACTION_EMAIL		"EMAIL"	
#define XMLFORMAT_CALENDAR_ALARM_ACTION_PROCEDURE	"PROCEDURE"	
#define XMLFORMAT_CALENDAR_ALARM_ATTACH			"AlarmAttach"
#define XMLFORMAT_CALENDAR_ALARM_ATTENDEE		"AlarmAttendee"
#define XMLFORMAT_CALENDAR_ALARM_DESCRIPTION		"AlarmDescription"
#define XMLFORMAT_CALENDAR_ALARM_REPEAT			"AlarmRepeat"
#define XMLFORMAT_CALENDAR_ALARM_REPEATDURATION		"AlarmRepeatDuration"
#define XMLFORMAT_CALENDAR_ALARM_SUMMARY		"AlarmSummary"
#define XMLFORMAT_CALENDAR_ALARM_TRIGGER		"AlarmTrigger"
#define XMLFORMAT_CALENDAR_ALARM_VALUE			"Value"
#define XMLFORMAT_CALENDAR_ALARM_RELATEDTYPE		"RelatedType"
#define XMLFORMAT_CALENDAR_ALARM_ALTERNATIVETEXTREP	"AlternativeTextRep"
#define XMLFORMAT_CALENDAR_ALARM_LANGUAGE		"Language"
#define XMLFORMAT_CALENDAR_ALARM_ATTACHVALUE		"AttachValue"
#define XMLFORMAT_CALENDAR_ALARM_FORMATTYPE		"FormatType"
#define XMLFORMAT_CALENDAR_ALARM_ENCODING		"Encoding"
#define XMLFORMAT_CALENDAR_
#define XMLFORMAT_CALENDAR_
#define XMLFORMAT_CALENDAR_
#define XMLFORMAT_CALENDAR_

// Attachment
#define XMLFORMAT_CALENDAR_ATTACHMENT			"Attachment"
#define XMLFORMAT_CALENDAR_ATTACHMENT_CONTENT		"Content"
#define XMLFORMAT_CALENDAR_ATTACHMENT_VALUE		"Value"
#define XMLFORMAT_CALENDAR_ATTACHMENT_FORMATTYPE	"FormatType"
#define XMLFORMAT_CALENDAR_ATTACHMENT_ENCODING		"Encoding"

// AttachmentType
#define XMLFORMAT_CALENDAR_ATTACHMENTTYPE		"AttachmentType"
#define XMLFORMAT_CALENDAR_ATTACHMENTTYPE_URI		"URI"
#define XMLFORMAT_CALENDAR_ATTACHMENTTYPE_BINARY	"BINARY"

// Attendee
#define XMLFORMAT_CALENDAR_ATTENDEE			"Attendee"
#define XMLFORMAT_CALENDAR_ATTENDEE_CONTENT		"Content"
#define XMLFORMAT_CALENDAR_ATTENDEE_CUTYPE		"CUType"
#define XMLFORMAT_CALENDAR_ATTENDEE_MEMBER		"Member"
#define XMLFORMAT_CALENDAR_ATTENDEE_ROLE		"Role"
#define XMLFORMAT_CALENDAR_ATTENDEE_PARTSTAT		"PartStat"
#define XMLFORMAT_CALENDAR_ATTENDEE_RSVP		"Rsvp"
#define XMLFORMAT_CALENDAR_ATTENDEE_DELEGATEDFROM	"DelegatedFrom"
#define XMLFORMAT_CALENDAR_ATTENDEE_SENTBY		"SentBy"
#define XMLFORMAT_CALENDAR_ATTENDEE_COMMONNAME		"CommonName"
#define XMLFORMAT_CALENDAR_ATTENDEE_DIRECTORY		"Directory"
#define XMLFORMAT_CALENDAR_ATTENDEE_LANGUAGE		"Language"

// BasicRecurrenceFreq
#define XMLFORMAT_CALENDAR_BASICRECURRENCEFREQ		"BasicRecurrenceFreq"
#define XMLFORMAT_CALENDAR_BASICRECURRENCEFREQ_DAILY	"DAILY"
#define XMLFORMAT_CALENDAR_BASICRECURRENCEFREQ_WEEKLY	"WEEKLY"
#define XMLFORMAT_CALENDAR_BASICRECURRENCEFREQ_MONTHLY	"MONTHLY"
#define XMLFORMAT_CALENDAR_BASICRECURRENCEFREQ_YEARLY	"YEARLY"

// CalendarUserType
#define XMLFORMAT_CALENDAR_CALENDARUSERTYPE		"CalendarUserType"
#define XMLFORMAT_CALENDAR_CALENDARUSERTYPE_INDIVIDUAL	"INDIVIDUAL"
#define XMLFORMAT_CALENDAR_CALENDARUSERTYPE_GROUP	"GROUP"
#define XMLFORMAT_CALENDAR_CALENDARUSERTYPE_RESOURCE	"RESOURCE"
#define XMLFORMAT_CALENDAR_CALENDARUSERTYPE_ROOM	"ROOM"
#define XMLFORMAT_CALENDAR_CALENDARUSERTYPE_UNKNOWN	"UNKNOWN"

// Duration
#define XMLFORMAT_CALENDAR_DURATION			"Duration"
#define XMLFORMAT_CALENDAR_DURATION_INADVANCE		"InAdvance"
#define XMLFORMAT_CALENDAR_DURATION_WEEKS		"Weeks"
#define XMLFORMAT_CALENDAR_DURATION_DAYS		"Days"
#define XMLFORMAT_CALENDAR_DURATION_HOURS		"Hours"
#define XMLFORMAT_CALENDAR_DURATION_MINUTES		"Minutes"
#define XMLFORMAT_CALENDAR_DURATION_SECONDS		"Seconds"

// IntegerContent
#define XMLFORMAT_CALENDAR_INTEGERCONTENT		"IntegerContent"
#define XMLFORMAT_CALENDAR_INTEGERCONTENT_CONTENT	"Content"

// Organizer
#define XMLFORMAT_CALENDAR_ORGANIZER			"Organizer"
#define XMLFORMAT_CALENDAR_ORGANIZER_CONTENT		"Content"
#define XMLFORMAT_CALENDAR_ORGANIZER_COMMONNAME		"CommonName"
#define XMLFORMAT_CALENDAR_ORGANIZER_DIRECTORY		"Directory"
#define XMLFORMAT_CALENDAR_ORGANIZER_SENTBY		"SentBy"
#define XMLFORMAT_CALENDAR_ORGANIZER_LANGUAGE		"Language"

// Priority
#define XMLFORMAT_CALENDAR_PRIORITY			"Priority"
#define XMLFORMAT_CALENDAR_PRIORITY_CONTENT		"Content"
#define XMLFORMAT_CALENDAR_PRIORITY_CONTENT_MAX		"9"
#define XMLFORMAT_CALENDAR_PRIORITY_CONTENT_MIN		"0"

// RecurrenceId
#define XMLFORMAT_CALENDAR_RECURRENCEID			"RecurrenceId"
#define XMLFORMAT_CALENDAR_RECURRENCEID_CONTENT		"Content"
#define XMLFORMAT_CALENDAR_RECURRENCEID_TIMEZONEID	"TimezoneID"
#define XMLFORMAT_CALENDAR_RECURRENCEID_RANGE		"Range"
#define XMLFORMAT_CALENDAR_RECURRENCEID_RANGE_THISANDPRIOR	"THISANDPRIOR"
#define XMLFORMAT_CALENDAR_RECURRENCEID_RANGE_THISANDFUTURE	"THISANDFUTURE"
#define XMLFORMAT_CALENDAR_RECURRENCEID_VALUE		"Value"

// RecurrenceRule
#define XMLFORMAT_CALENDAR_RECURRENCERULE		"RecurrenceRule"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_FREQUENCY	"Frequency"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_UNTIL		"Until"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_COUNT		"Count"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_INTERVAL	"Interval"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_BYDAY		"ByDay"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_BYMONTHDAY	"ByMonthDay"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_BYYEARDAY	"ByYearDay"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_BYMONTH	"ByMonth"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_TIMEZONEID	"TimezoneID"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_TZCOMPONENT	"TZComponent"

// RelatedType
#define XMLFORMAT_CALENDAR_RELATEDTYPE			"RelatedType"
#define XMLFORMAT_CALENDAR_RELATEDTYPE_START		"START"
#define XMLFORMAT_CALENDAR_RELATEDTYPE_END		"END"

// RelatedTo
#define XMLFORMAT_CALENDAR_RELATEDTO			"RelatedTo"
#define XMLFORMAT_CALENDAR_RELATEDTO_CONTENT		"Content"
#define XMLFORMAT_CALENDAR_RELATEDTO_TIMEZONEID		"TimezoneID"
#define XMLFORMAT_CALENDAR_RELATEDTO_RELATIONSHIPTYPE	"RelationshipType"

// RelationshipType
#define XMLFORMAT_CALENDAR_RELATIONSHIPTYPE		"RelationshipType"
#define XMLFORMAT_CALENDAR_RELATIONSHIPTYPE_PARENT	"PARENT"
#define XMLFORMAT_CALENDAR_RELATIONSHIPTYPE_CHILD	"CHILD"
#define XMLFORMAT_CALENDAR_RELATIONSHIPTYPE_SIBLING	"SIBLING"

// RequestStatus
#define XMLFORMAT_CALENDAR_REQUESTSTATUS		"RequestStatus"
#define XMLFORMAT_CALENDAR_REQUESTSTATUS_STATUSCODE	"StatusCode"
#define XMLFORMAT_CALENDAR_REQUESTSTATUS_STATUSDESCRIPTION	"StatusDescription"
#define XMLFORMAT_CALENDAR_REQUESTSTATUS_EXCEPTIONDATA	"ExceptionData"
#define XMLFORMAT_CALENDAR_REQUESTSTATUS_TIMEZONEID	"TimezoneID"
#define XMLFORMAT_CALENDAR_REQUESTSTATUS_RELATIONSHIPTYPE	"RelationshipType"

// RoleType
#define XMLFORMAT_CALENDAR_ROLETYPE			"RoleType"
#define XMLFORMAT_CALENDAR_ROLETYPE_NEEDSACTION		"NEEDS-ACTION"
#define XMLFORMAT_CALENDAR_ROLETYPE_ACCEPTED		"ACCEPTED"
#define XMLFORMAT_CALENDAR_ROLETYPE_DECLINED		"DECLINED"
#define XMLFORMAT_CALENDAR_ROLETYPE_TENTATIVE		"TENTATIVE"
#define XMLFORMAT_CALENDAR_ROLETYPE_DELEGATED		"DELEGATED"

// Status
#define XMLFORMAT_CALENDAR_STATUS			"Status"
#define XMLFORMAT_CALENDAR_STATUS_CONTENT		"Content"
#define XMLFORMAT_CALENDAR_STATUS_CONTENT_TENTATIVE	"TENTATIVE"
#define XMLFORMAT_CALENDAR_STATUS_CONTENT_CONFIRMED	"CONFIRMED"
#define XMLFORMAT_CALENDAR_STATUS_CONTENT_CANCELLED	"CANCELLED"

// TriggerType
#define XMLFORMAT_CALENDAR_TRIGGERTYPE			"TriggerType"
#define XMLFORMAT_CALENDAR_TRIGGERTYPE_DATETIME		"DATE-TIME"
#define XMLFORMAT_CALENDAR_TRIGGERTYPE_DURATION		"DURATION"

// UrlContent
#define XMLFORMAT_CALENDAR_URLCONTENT			"UrlContent"
#define XMLFORMAT_CALENDAR_URLCONTENT_CONTENT		"Content"

#endif /* XMLFORMAT_CALENDAR_H */
