/*
 * xmlformat - registration of xml object formats 
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 * 
 */

#include "xmlformat-common.h"

#ifndef XMLFORMAT_CALENDAR_H
#define XMLFORMAT_CALENDAR_H

#define XMLFORMAT_CALENDAR_ROOT				"note"
#define XMLFORMAT_CALENDAR_VERSION			"version"

// Attachment
#define XMLFORMAT_CALENDAR_ATTACHMENT			"Attachment"
#define XMLFORMAT_CALENDAR_ATTACHMENT_CONTENT		"Content"
#define XMLFORMAT_CALENDAR_ATTACHMENT_VALUE		"Value"
#define XMLFORMAT_CALENDAR_ATTACHMENT_VALUE_URI		"URI"
#define XMLFORMAT_CALENDAR_ATTACHMENT_VALUE_BINARY	"BINARY"
#define XMLFORMAT_CALENDAR_ATTACHMENT_FORMATTYPE	"FormatType"
#define XMLFORMAT_CALENDAR_ATTACHMENT_ENCODING		"Encoding"

// Attendee
#define XMLFORMAT_CALENDAR_ATTENDEE			"Attendee"
#define XMLFORMAT_CALENDAR_ATTENDEE_CONTENT		"Content"
#define XMLFORMAT_CALENDAR_ATTENDEE_CUTYPE		"CUType"
#define XMLFORMAT_CALENDAR_ATTENDEE_MEMBER		"Member"
#define XMLFORMAT_CALENDAR_ATTENDEE_ROLE		"Role"
#define XMLFORMAT_CALENDAR_ATTENDEE_PARTSTAT		"PartStat"
#define XMLFORMAT_CALENDAR_ATTENDEE_RSVP		"Rsvp"
#define XMLFORMAT_CALENDAR_ATTENDEE_DELEGATEDFROM	"DelegatedFrom"
#define XMLFORMAT_CALENDAR_ATTENDEE_SENTBY		"SentBy"
#define XMLFORMAT_CALENDAR_ATTENDEE_COMMONNAME		"CommonName"
#define XMLFORMAT_CALENDAR_ATTENDEE_DIRECTORY		"Directory"
#define XMLFORMAT_CALENDAR_ATTENDEE_LANGUAGE		"Language"

// BasicRecurrenceFreq
#define XMLFORMAT_CALENDAR_BASICRECURRENCEFREQ		"BasicRecurrenceFreq"
#define XMLFORMAT_CALENDAR_BASICRECURRENCEFREQ_DAILY	"DAILY"
#define XMLFORMAT_CALENDAR_BASICRECURRENCEFREQ_WEEKLY	"WEEKLY"
#define XMLFORMAT_CALENDAR_BASICRECURRENCEFREQ_MONTHLY	"MONTHLY"
#define XMLFORMAT_CALENDAR_BASICRECURRENCEFREQ_YEARLY	"YEARLY"

// CalendarUserType
#define XMLFORMAT_CALENDAR_CALENDARUSERTYPE		"CalendarUserType"
#define XMLFORMAT_CALENDAR_CALENDARUSERTYPE_INDIVIDUAL	"INDIVIDUAL"
#define XMLFORMAT_CALENDAR_CALENDARUSERTYPE_GROUP	"GROUP"
#define XMLFORMAT_CALENDAR_CALENDARUSERTYPE_RESOURCE	"RESOURCE"
#define XMLFORMAT_CALENDAR_CALENDARUSERTYPE_ROOM	"ROOM"
#define XMLFORMAT_CALENDAR_CALENDARUSERTYPE_UNKNOWN	"UNKNOWN"

// RecurrenceRule
#define XMLFORMAT_CALENDAR_RECURRENCERULE		"RecurrenceRule"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_FREQUENCY	"Frequency"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_UNTIL		"Until"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_COUNT		"Count"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_INTERVAL	"Interval"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_BYDAY		"ByDay"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_BYMONTHDAY	"ByMonthDay"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_BYYEARDAY	"ByYearDay"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_BYMONTH	"ByMonth"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_TIMEZONEID	"TimezoneID"
#define XMLFORMAT_CALENDAR_RECURRENCERULE_TZCOMPONENT	"TZComponent"

// IntegerContent
#define XMLFORMAT_CALENDAR_INTEGERCONTENT		"IntegerContent"
#define XMLFORMAT_CALENDAR_INTEGERCONTENT_CONTENT	"Content"

// Organizer
#define XMLFORMAT_CALENDAR_ORGANIZER			"Organizer"
#define XMLFORMAT_CALENDAR_ORGANIZER_CONTENT		"Content"
#define XMLFORMAT_CALENDAR_ORGANIZER_COMMONNAME		"CommonName"
#define XMLFORMAT_CALENDAR_ORGANIZER_DIRECTORY		"Directory"
#define XMLFORMAT_CALENDAR_ORGANIZER_SENTBY		"SentBy"
#define XMLFORMAT_CALENDAR_ORGANIZER_LANGUAGE		"Language"

// RecurrenceId
#define XMLFORMAT_CALENDAR_RECURRENCEID			"RecurrenceId"
#define XMLFORMAT_CALENDAR_RECURRENCEID_CONTENT		"Content"
#define XMLFORMAT_CALENDAR_RECURRENCEID_TIMEZONEID	"TimezoneID"
#define XMLFORMAT_CALENDAR_RECURRENCEID_RANGE		"Range"
#define XMLFORMAT_CALENDAR_RECURRENCEID_RANGE_THISANDPRIOR	"THISANDPRIOR"
#define XMLFORMAT_CALENDAR_RECURRENCEID_RANGE_THISANDFUTURE	"THISANDFUTURE"
#define XMLFORMAT_CALENDAR_RECURRENCEID_VALUE		"Value"

// RelationshipType
#define XMLFORMAT_CALENDAR_RELATIONSHIPTYPE		"RelationshipType"
#define XMLFORMAT_CALENDAR_RELATIONSHIPTYPE_PARENT	"PARENT"
#define XMLFORMAT_CALENDAR_RELATIONSHIPTYPE_CHILD	"CHILD"
#define XMLFORMAT_CALENDAR_RELATIONSHIPTYPE_SIBLING	"SIBLING"

// RelatedTo
#define XMLFORMAT_CALENDAR_RELATEDTO			"RelatedTo"
#define XMLFORMAT_CALENDAR_RELATEDTO_CONTENT		"Content"
#define XMLFORMAT_CALENDAR_RELATEDTO_TIMEZONEID		"TimezoneID"
#define XMLFORMAT_CALENDAR_RELATEDTO_RELATIONSHIPTYPE	"RelationshipType"

// RequestStatus
#define XMLFORMAT_CALENDAR_REQUESTSTATUS		"RequestStatus"
#define XMLFORMAT_CALENDAR_REQUESTSTATUS_STATUSCODE	"StatusCode"
#define XMLFORMAT_CALENDAR_REQUESTSTATUS_STATUSDESCRIPTION	"StatusDescription"
#define XMLFORMAT_CALENDAR_REQUESTSTATUS_EXCEPTIONDATA	"ExceptionData"
#define XMLFORMAT_CALENDAR_REQUESTSTATUS_TIMEZONEID	"TimezoneID"
#define XMLFORMAT_CALENDAR_REQUESTSTATUS_RELATIONSHIPTYPE	"RelationshipType"

// RoleType
#define XMLFORMAT_CALENDAR_ROLETYPE			"RoleType"
#define XMLFORMAT_CALENDAR_ROLETYPE_NEEDSACTION		"NEEDS-ACTION"
#define XMLFORMAT_CALENDAR_ROLETYPE_ACCEPTED		"ACCEPTED"
#define XMLFORMAT_CALENDAR_ROLETYPE_DECLINED		"DECLINED"
#define XMLFORMAT_CALENDAR_ROLETYPE_TENTATIVE		"TENTATIVE"
#define XMLFORMAT_CALENDAR_ROLETYPE_DELEGATED		"DELEGATED"

// Status
#define XMLFORMAT_CALENDAR_STATUS			"Status"
#define XMLFORMAT_CALENDAR_STATUS_CONTENT		"Content"
#define XMLFORMAT_CALENDAR_STATUS_CONTENT_TENTATIVE	"TENTATIVE"
#define XMLFORMAT_CALENDAR_STATUS_CONTENT_CONFIRMED	"CONFIRMED"
#define XMLFORMAT_CALENDAR_STATUS_CONTENT_CANCELLED	"CANCELLED"

// UrlContent
#define XMLFORMAT_CALENDAR_URLCONTENT			"UrlContent"
#define XMLFORMAT_CALENDAR_URLCONTENT_CONTENT		"Content"

#define XMLFORMAT_CALENDAR_
#define XMLFORMAT_CALENDAR_
#define XMLFORMAT_CALENDAR_
#define XMLFORMAT_CALENDAR_
#define XMLFORMAT_CALENDAR_
#define XMLFORMAT_CALENDAR_
#define XMLFORMAT_CALENDAR_
#define XMLFORMAT_CALENDAR_
#define XMLFORMAT_CALENDAR_
#define XMLFORMAT_CALENDAR_
#define XMLFORMAT_CALENDAR_


#endif /* XMLFORMAT_CALENDAR_H */
