Import('*')

if env['enable_rpath'] == 1:
	env.Append( LINKFLAGS = [r'-Wl,--rpath', r'-Wl,$prefix/$libsuffix/opensync/formats'] )

#env.Append( LINKFLAGS = [r'-L$prefix/$libsuffix/opensync/formats'] )
env.Append( CPPPATH = '.' )

# basic vformat plugins
opie = env.SharedLibrary('opie', ['opie_format.c', 'opie_xml_utils.c'])
opie_sync = env.SharedLibrary('opie-sync', ['opie_sync.c', 'opie_qcop.c', 'opie_comms.c', 'opie_xml.c', 'opie_xml_utils.c', 'md5.c'])


# install synchronization plugin and config 
env.Install(install_plugin, opie_sync)
env.Install(install_config, ['opie-sync'])	

# install format plugin
env.Install(install_format, opie)

env.Alias('install', install_prefix)
