# - Try to find the GMODULE2 libraries
# Once done this will define
#
#  GMODULE2_FOUND - system has gmodule2
#  GMODULE2_INCLUDE_DIR - the gmodule2 include directory
#  GMODULE2_LIBRARIES - gmodule2 library

IF ( GMODULE2_INCLUDE_DIR AND GMODULE2_LIBRARIES )
    SET(GMODULE2_FIND_QUIETLY TRUE )
ENDIF ( GMODULE2_INCLUDE_DIR AND GMODULE2_LIBRARIES )

IF ( NOT WIN32 )
   INCLUDE( UsePkgConfig )
   PKGCONFIG( gmodule-2.0 _LibGMODULE2IncDir _LibGMODULE2LinkDir _LibGMODULE2LinkFlags _LibGMODULE2Cflags )
ENDIF ( NOT WIN32 )

# Look for gmodule2 include dir and libraries
FIND_PATH( GMODULE2_INCLUDE_DIR gmodule.h PATH_SUFFIXES glib-2.0 PATHS ${_LibGMODULE2IncDir} )

FIND_LIBRARY( GMODULE2_LIBRARIES NAMES gmodule-2.0 PATHS ${_LibGMODULE2LinkDir} )

IF ( GMODULE2_INCLUDE_DIR AND GMODULE2_LIBRARIES )
	IF ( NOT GMODULE2_FIND_QUIETLY )
		MESSAGE ( STATUS "Found gmodule2: ${GMODULE2_LIBRARIES}" )
	ENDIF ( NOT GMODULE2_FIND_QUIETLY )
ELSE ( GMODULE2_INCLUDE_DIR AND GMODULE2_LIBRARIES )
	IF ( NOT GMODULE2_FIND_QUIETLY )
		MESSAGE ( STATUS "Could NOT found gmodule2." )
	ENDIF ( NOT GMODULE2_FIND_QUIETLY )
ENDIF ( GMODULE2_INCLUDE_DIR AND GMODULE2_LIBRARIES )

# Hide advanced variables from CMake GUIs
MARK_AS_ADVANCED( GMODULE2_INCLUDE_DIR GMODULE2_LIBRARIES )

