Import('*')

if testenv.has_key('enable_tests') and testenv['enable_tests'] == 1:
	binary = testenv.Program('osyncbinary', ['osyncbinary.c'], LIBS = ['opensync'], LIBPATH = '#opensync')
	dump = testenv.Program('osyncdump', ['osyncdump.c'], LIBS = ['opensync'], LIBPATH = '#opensync')
	#testenv.Program('osyncplugin', ['osyncplugin.c'], LIBS = ['opensync'], LIBPATH = '#opensync')
	#testenv.Program('osyncstress', ['osyncstress.c'], LIBS = ['opensync'], LIBPATH = '#opensync')
	#testenv.Program('osynctest', ['osynctest.c'], LIBS = ['opensync'], LIBPATH = '#opensync')
	
	env.Install(install_bin, binary)
	env.Install(install_bin, dump)
	env.Alias('install', install_prefix)
